# Generated by Django 4.2.7 on 2024-04-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboad', '0004_quizcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcategory',
            name='image',
            field=models.ImageField(upload_to='cat_imgs/'),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('opt_1', models.CharField(max_length=200)),
                ('opt_2', models.CharField(max_length=200)),
                ('opt_3', models.CharField(max_length=200)),
                ('opt_4', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('time_limit', models.IntegerField()),
                ('right_opt', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboad.quizcategory')),
            ],
        ),
    ]
