# Generated by Django 4.2.7 on 2024-04-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboad', '0005_alter_quizcategory_image_quizquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizcategory',
            options={'verbose_name_plural': 'Quiz Categories'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name_plural': 'Quiz Questions'},
        ),
    ]
